#xhost +local:

services:
  ros2_gazebo:
    build: .
    privileged: true
    entrypoint: "/root/data/project_ws/build2.sh"
#    entrypoint: "terminator"
    network_mode: host  
    environment:
      - DISPLAY
      - IS_DEBUGGER=True
    volumes:
      - ./data:/root/data
      - /dev/input:/dev/input
