#   xhost +local:

services:
  ros2_gazebo:
    build: .
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: "terminator"
    network_mode: host  
    ipc: "host"
    pid: "host"
    #cpuset: "1-5"
    environment:
      - IS_SIM=True
      - DISPLAY
    volumes:
      - ./data:/root/data
      - /dev/input:/dev/input
